language: php

php:
  - 5.6
  - 7.0
  - 7.1
  - 7.2
  - 7.3
  - 7.4

matrix:
  include:
    - php: 5.3
      dist: precise
    - php: 5.4
      dist: precise
    - php: 5.5
      dist: precise
  allow_failures:
    - php: 7.2
    - php: 7.3
    - php: 7.4

sudo: false

install:
    - COMPOSER_MEMORY_LIMIT=-1 composer install --prefer-source -n --ignore-platform-reqs

script:
    - vendor/bin/php-cs-fixer fix -v --dry-run .
    - vendor/bin/phpcs --standard=PSR2 -p --extensions=php Gass/ Tests/
    - vendor/bin/phpunit -c Tests/phpunit.xml.dist --verbose --coverage-clover clover.xml

after_script:
    - php vendor/bin/coveralls -v
