language: php

php:
  - hhvm
  - 5.6
  - 5.3
  - 5.4
  - 5.5

matrix:
  allow_failures:
    - php: hhvm
    - php: 5.6

install:
    - composer install --dev --prefer-source

script:
    - vendor/bin/php-cs-fixer fix -v --dry-run .
    - vendor/bin/phpcs --standard=PSR2 -p --extensions=php Gass/ Tests/
    - vendor/bin/phpunit --configuration=Tests/phpunit.xml.dist Tests/