language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - 7.1
  - hhvm
  - nightly

matrix:
  allow_failures:
    - php: hhvm
    - php: nightly

sudo: false

install:
    - composer install --prefer-source -n

script:
    - vendor/bin/php-cs-fixer fix -v --dry-run .
    - vendor/bin/phpcs --standard=PSR2 -p --extensions=php Gass/ Tests/
    - vendor/bin/phpunit -c Tests/phpunit.xml.dist --verbose --coverage-clover clover.xml

after_script:
    - php vendor/bin/coveralls -v
